import {
  Badge,
  Box,
  Card,
  Heading,
  Stack,
  Text,
  Timeline,
} from "@chakra-ui/react";
import {
  LuBrain,
  LuDatabase,
  LuKeyboard,
  LuMonitor,
  LuTable,
} from "react-icons/lu";
import { publishedDatasets } from "~/lib/datasets";

export default function AboutPage() {
  return (
    <Box h="full" w="full" overflow="auto">
      <Stack
        direction="column"
        maxW="3xl"
        mx="auto"
        px={{ base: "4", md: "8" }}
        py={{ base: "8", md: "12" }}
        gap="12"
      >
        <Intro />
        <AgentFlow />
        <Datasets />
      </Stack>
    </Box>
  );
}

function Intro() {
  return (
    <Stack direction="column" gap="4">
      <Heading size="2xl">How bankql works</Heading>
      <Text color="fg.muted" textStyle="lg">
        bankql is a browser-native exploration tool for U.S. banking data.
        FDIC, NCUA, and Federal Reserve datasets are pre-processed into
        Parquet files, then loaded directly into a SQL engine running inside
        your tab.
      </Text>
      <Text color="fg.muted">
        That means every query — typed by hand or generated by the assistant —
        runs locally against your own copy of the data. Nothing about your
        questions or your results is sent to a server.
      </Text>
    </Stack>
  );
}

function AgentFlow() {
  return (
    <Stack direction="column" gap="6">
      <Stack direction="column" gap="1">
        <Heading size="lg">The agent flow</Heading>
        <Text color="fg.muted">
          Ask a question in plain English. Here is what happens next.
        </Text>
      </Stack>

      <Timeline.Root size="lg" variant="subtle">
        <Timeline.Item>
          <Timeline.Connector>
            <Timeline.Separator />
            <Timeline.Indicator>
              <LuKeyboard />
            </Timeline.Indicator>
          </Timeline.Connector>
          <Timeline.Content>
            <Timeline.Title>You ask a question</Timeline.Title>
            <Timeline.Description>
              Natural language — &ldquo;which credit unions in Michigan grew
              fastest last year?&rdquo;
            </Timeline.Description>
          </Timeline.Content>
        </Timeline.Item>

        <Timeline.Item>
          <Timeline.Connector>
            <Timeline.Separator />
            <Timeline.Indicator>
              <LuBrain />
            </Timeline.Indicator>
          </Timeline.Connector>
          <Timeline.Content>
            <Timeline.Title>An LLM proposes SQL</Timeline.Title>
            <Timeline.Description>
              Your prompt — and only your prompt — goes to Claude on Azure.
              The model sees the dataset schemas, not the data, and returns a
              <Badge ml="2" variant="subtle">
                query_data
              </Badge>{" "}
              tool call with a SQL statement.
            </Timeline.Description>
          </Timeline.Content>
        </Timeline.Item>

        <Timeline.Item>
          <Timeline.Connector>
            <Timeline.Separator />
            <Timeline.Indicator>
              <LuDatabase />
            </Timeline.Indicator>
          </Timeline.Connector>
          <Timeline.Content>
            <Timeline.Title>DuckDB-WASM runs it locally</Timeline.Title>
            <Timeline.Description>
              The SQL is executed against an in-browser DuckDB instance backed
              by Parquet files cached in OPFS. No round-trip — the rows never
              leave your machine.
            </Timeline.Description>
          </Timeline.Content>
        </Timeline.Item>

        <Timeline.Item>
          <Timeline.Connector>
            <Timeline.Separator />
            <Timeline.Indicator>
              <LuMonitor />
            </Timeline.Indicator>
          </Timeline.Connector>
          <Timeline.Content>
            <Timeline.Title>Results stream back to the chat</Timeline.Title>
            <Timeline.Description>
              The tool result is handed back to the model, which writes a
              short explanation alongside the table. You can keep iterating
              without ever leaving the browser.
            </Timeline.Description>
          </Timeline.Content>
        </Timeline.Item>
      </Timeline.Root>
    </Stack>
  );
}

function Datasets() {
  return (
    <Stack direction="column" gap="6">
      <Stack direction="column" gap="1">
        <Heading size="lg">Available datasets</Heading>
        <Text color="fg.muted">
          Each dataset is published as a single Parquet file and loaded once
          per browser. Schema and row types are derived from a single
          definition in <Badge variant="subtle">@bankql/schema</Badge>.
        </Text>
      </Stack>

      <Stack direction="column" gap="3">
        {publishedDatasets.map((dataset) => (
          <Card.Root key={dataset.name} variant="outline">
            <Card.Body>
              <Stack direction="row" align="center" gap="3" mb="2">
                <Box color="fg.muted">
                  <LuTable />
                </Box>
                <Card.Title fontFamily="mono" fontSize="md">
                  {dataset.name}
                </Card.Title>
                <Badge variant="subtle">
                  {Object.keys(dataset.fields).length} columns
                </Badge>
              </Stack>
              {dataset.description && (
                <Card.Description>{dataset.description}</Card.Description>
              )}
            </Card.Body>
          </Card.Root>
        ))}
      </Stack>
    </Stack>
  );
}
